-- Beyond multi-club ML feature layer v1
--
-- Purpose:
-- - normalize completed home-match outcomes across clubs;
-- - store model features exactly as they were knowable at canonical horizons;
-- - make point-in-time/no-leakage a persisted data contract rather than a
--   convention hidden in one training script.
--
-- These tables are backend/ML only. They are deliberately not exposed to anon
-- or authenticated dashboard clients.

create table if not exists public.ml_match_history (
  id bigint generated by default as identity primary key,
  club_slug text not null,
  external_match_key text not null,
  season text not null,
  competition text not null,
  competition_key text,
  home_team text not null,
  away_team text not null,
  opponent_key text not null,
  kickoff_at timestamptz not null,
  actual_attendance integer not null check (actual_attendance >= 0),
  attendance_definition text not null,
  stadium_capacity integer check (stadium_capacity is null or stadium_capacity > 0),
  source_name text not null,
  source_url text,
  source_observed_at timestamptz,
  source_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (club_slug, external_match_key),
  check (home_team <> away_team)
);

create index if not exists ml_match_history_club_kickoff_idx
  on public.ml_match_history (club_slug, kickoff_at);
create index if not exists ml_match_history_club_season_idx
  on public.ml_match_history (club_slug, season);
create index if not exists ml_match_history_competition_idx
  on public.ml_match_history (competition_key, kickoff_at);

create table if not exists public.ml_feature_snapshots (
  id bigint generated by default as identity primary key,
  match_history_id bigint not null
    references public.ml_match_history(id) on delete cascade,
  horizon text not null check (horizon in ('T-30','T-14','T-7','T-3','T-24h')),
  as_of_at timestamptz not null,
  feature_set_version text not null,
  features jsonb not null,
  feature_sources jsonb not null default '{}'::jsonb,
  point_in_time_validated boolean not null default false,
  validation_notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (match_history_id, horizon, feature_set_version)
);

create index if not exists ml_feature_snapshots_horizon_version_idx
  on public.ml_feature_snapshots (horizon, feature_set_version);
create index if not exists ml_feature_snapshots_match_idx
  on public.ml_feature_snapshots (match_history_id);

alter table public.ml_match_history enable row level security;
alter table public.ml_feature_snapshots enable row level security;

-- Explicitly keep backend training data out of browser roles. service_role and
-- database owner retain server-side access; no permissive RLS policies are added.
revoke all on table public.ml_match_history from anon, authenticated;
revoke all on table public.ml_feature_snapshots from anon, authenticated;
revoke all on sequence public.ml_match_history_id_seq from anon, authenticated;
revoke all on sequence public.ml_feature_snapshots_id_seq from anon, authenticated;

grant select, insert, update, delete on table public.ml_match_history to service_role;
grant select, insert, update, delete on table public.ml_feature_snapshots to service_role;
grant usage, select on sequence public.ml_match_history_id_seq to service_role;
grant usage, select on sequence public.ml_feature_snapshots_id_seq to service_role;

comment on table public.ml_match_history is
  'Normalized completed home-match outcomes used by Beyond multi-club historical models.';
comment on table public.ml_feature_snapshots is
  'Versioned point-in-time ML feature snapshots at canonical pre-match horizons.';
comment on column public.ml_feature_snapshots.as_of_at is
  'Knowledge cutoff for this feature snapshot. No feature may depend on information first known after this timestamp.';
comment on column public.ml_feature_snapshots.point_in_time_validated is
  'True only after leakage checks confirm every feature existed at as_of_at.';
